ckeditor5.plugin.ckeditor_mentions_mentions:
  type: config_object
  label: 'CKE Mention Settings'
  mapping:
    plugins:
      type: sequence
      label: 'Mentions plugin settings'
      sequence:
        type: ckeditor5.plugin.ckeditor_mentions_mentions.plugin

ckeditor5.plugin.ckeditor_mentions_mentions.plugin:
  type: mapping
  label: 'Mentions plugin settings'
  mapping:
    id:
      type: string
      label: 'Plugin ID'
    enable:
      type: boolean
      label: 'Status'
    mentions_type:
      type: string
      label: 'Type of mentions'
    charcount:
      type: integer
      label: 'Characters count'
    dropdownLimit:
      type: integer
      label: 'dropdownLimit'
    timeout:
      type: integer
      label: 'Timeout'
    marker:
      type: string
      label: 'Marker'
    use_advanced_pattern:
      type: boolean
      label: 'Use advanced pattern?'
    pattern:
      type: string
      label: 'Pattern'
    advanced_pattern:
      type: string
      label: 'Advanced pattern'
