ckeditor.plugin.mentions:
  type: mapping
  label: 'Configurations'
  mapping:
    enable:
      type: boolean
      label: 'Status'
    mentions_type:
      type: string
      label: 'Type of mentions'
    charcount:
      type: integer
      label: 'Characters count'
    timeout:
      type: integer
      label: 'Timeout'
    marker:
      type: string
      label: 'Marker'
    use_advanced_pattern:
      type: boolean
      label: 'Use advanced pattern?'
    pattern:
      type: string
      label: 'Pattern'
    advanced_pattern:
      type: string
      label: 'Advanced pattern'
